[SYS_CONFIG]
#调试等级
debug=100
#日志级别，debug warnning error
log_level=warnning
#日志模式 verbose normal debug
log_mode=normal
#日志目录
log_path=/opt/uni/log
#x86 boardID
self_id=0x0010
#升级文件存放目录
ota_path=/opt/uni/otafile


[SYS_HOTSIMULATION]
#是否直接从配置文件加载热模拟板的IP地址 yes/no
load_ip_from_config=no
#热模拟板对本机的服务IP地址
hotsimulation_ip_addr=127.0.0.1
#热模拟板对本机的服务端口号
hotsimulation_port=13083
#热模拟板心跳超时时间（秒）
hotsimulation_timeout=30


